/**
 * Checkout tier regression suite (QA, 2026-07-25), bug CHECKOUT-TIER-1.
 *
 * FIRST coverage for a surface that shipped on 2026-06-26 (commit 512488f,
 * "bootstrap Stripe Payment Links API + checkout thank-you route") and was
 * born broken. Nothing in the suite had ever exercised the tier round-trip:
 * `CheckoutThankYouPage.tsx` appeared only in the repo-wide structural sweep
 * `pageAnatomy.test.ts`, never in a behaviour test, and
 * `scripts/setup-stripe-payment-links.mjs` had no coverage at all.
 *
 * THE DEFECT
 * ----------
 * The generator built Stripe's `after_completion.redirect.url` as
 *
 *     const url = new URL(THANK_YOU_URL)   // .../infraportal/#/checkout-thank-you
 *     url.searchParams.set('tier', slug)
 *
 * `URL.searchParams` writes the SEARCH component, which the URL grammar places
 * BEFORE the fragment, so the customer was sent to
 * `.../infraportal/?tier=<slug>#/checkout-thank-you` while the page read the
 * tier out of `window.location.hash`. The tier never arrived and every paying
 * customer saw the generic "your engagement" fallback.
 *
 * TWO HALVES, BOTH GUARDED HERE
 * -----------------------------
 * 1. `scripts/lib/checkoutRedirect.mjs` now writes the parameter INSIDE the
 *    fragment, the hash-router convention `features/apiDocs/deepLink.ts`
 *    already documents. Guarded by real behaviour tests against the actual
 *    module the script imports, plus a drift guard reading the SCRIPT source
 *    so reintroducing the broken construction there reddens even though the
 *    shared module stays correct.
 * 2. `readCheckoutTier` also accepts the tier from the search component,
 *    because the three payment links live on Stripe today were generated by
 *    the broken code path and their redirect URL is stored on Stripe's side.
 *    Regenerating them is a USER-ONLY paid-account action, so the page has to
 *    keep working for links already in the wild.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { buildCheckoutRedirectUrl } from '../../../scripts/lib/checkoutRedirect.mjs'
import {
  FALLBACK_TIER_LABEL,
  TIER_PARAM,
  UNKNOWN_TIER_PARAM,
  checkoutLandingParams,
  checkoutTierLabel,
  formatTierLabel,
  readCheckoutTier,
} from './checkoutTier'

const ROOT = process.cwd()
const GENERATOR_SOURCE = 'scripts/setup-stripe-payment-links.mjs'
const LINKS_ARTIFACT = 'public/content/stripe_payment_links.json'

/** The production thank-you URL the generator defaults to. */
const THANK_YOU_URL = 'https://rodmen07.github.io/infraportal/#/checkout-thank-you'

/** The three slugs the generator actually emits (public/content/pricing.json). */
const LIVE_SLUGS = ['architecture-review', 'project-deposit', 'retainer-weekly']

function readSource(relative: string): string {
  return readFileSync(path.join(ROOT, relative), 'utf8')
}

/** Splits an absolute URL the way a browser hands it to the page. */
function asLocation(url: string): { hash: string; search: string } {
  const parsed = new URL(url)
  return { hash: parsed.hash, search: parsed.search }
}

describe('readCheckoutTier', () => {
  it('reads the tier from the hash query, the shape the fixed generator emits', () => {
    expect(readCheckoutTier('#/checkout-thank-you?tier=retainer-weekly')).toBe('retainer-weekly')
  })

  it('reads the tier from the search component, the shape live Stripe links still use', () => {
    expect(readCheckoutTier('#/checkout-thank-you', '?tier=project-deposit')).toBe('project-deposit')
  })

  it('accepts a search string with no leading question mark', () => {
    expect(readCheckoutTier('#/checkout-thank-you', 'tier=project-deposit')).toBe('project-deposit')
  })

  it('prefers the hash when both sources carry a tier', () => {
    expect(readCheckoutTier('#/checkout-thank-you?tier=from-hash', '?tier=from-search')).toBe(
      'from-hash',
    )
  })

  it('returns null when neither source carries a tier', () => {
    expect(readCheckoutTier('#/checkout-thank-you')).toBeNull()
    expect(readCheckoutTier('#/checkout-thank-you', '?session_id=cs_test_123')).toBeNull()
  })

  it('treats a blank tier as absent rather than rendering an empty phrase', () => {
    expect(readCheckoutTier('#/checkout-thank-you?tier=')).toBeNull()
    expect(readCheckoutTier('#/checkout-thank-you?tier=%20%20')).toBeNull()
  })

  it('ignores other parameters sharing the query', () => {
    expect(readCheckoutTier('#/checkout-thank-you?session_id=cs_1&tier=retainer-weekly')).toBe(
      'retainer-weekly',
    )
  })

  it('decodes a percent-encoded slug', () => {
    expect(readCheckoutTier('#/checkout-thank-you?tier=architecture%2Dreview')).toBe(
      'architecture-review',
    )
  })
})

describe('formatTierLabel', () => {
  it('renders a slug as title-cased prose', () => {
    expect(formatTierLabel('retainer-weekly')).toBe('Retainer Weekly')
    expect(formatTierLabel('architecture-review')).toBe('Architecture Review')
  })

  it('falls back to a neutral phrase when the tier is missing', () => {
    expect(formatTierLabel(null)).toBe(FALLBACK_TIER_LABEL)
    expect(formatTierLabel('   ')).toBe(FALLBACK_TIER_LABEL)
  })
})

describe('buildCheckoutRedirectUrl', () => {
  it('puts the parameter INSIDE the fragment for a hash-router URL', () => {
    expect(buildCheckoutRedirectUrl(THANK_YOU_URL, { tier: 'retainer-weekly' })).toBe(
      'https://rodmen07.github.io/infraportal/#/checkout-thank-you?tier=retainer-weekly',
    )
  })

  it('uses the search component when the base URL has no fragment', () => {
    expect(buildCheckoutRedirectUrl('https://example.com/thanks', { tier: 'a' })).toBe(
      'https://example.com/thanks?tier=a',
    )
  })

  it('preserves a query the fragment already carries and overwrites a repeated key', () => {
    expect(buildCheckoutRedirectUrl('https://e.com/#/x?a=1&tier=old', { tier: 'new' })).toBe(
      'https://e.com/#/x?a=1&tier=new',
    )
  })

  it('leaves an existing search component untouched', () => {
    const built = buildCheckoutRedirectUrl('https://e.com/?keep=1#/x', { tier: 'b' })
    expect(new URL(built).searchParams.get('keep')).toBe('1')
    expect(new URL(built).hash).toBe('#/x?tier=b')
  })
})

describe('generator to page round-trip (the defect, end to end)', () => {
  it.each(LIVE_SLUGS)('a customer redirected after buying %s sees that tier', (slug) => {
    const redirect = buildCheckoutRedirectUrl(THANK_YOU_URL, { [TIER_PARAM]: slug })
    const { hash, search } = asLocation(redirect)

    expect(readCheckoutTier(hash, search)).toBe(slug)
    expect(checkoutTierLabel(hash, search)).not.toBe(FALLBACK_TIER_LABEL)
  })

  it('the fixed URL is readable from the hash ALONE, with no search fallback', () => {
    // The compatibility path must not be what makes the new links work; if it
    // were, this suite would pass even if the generator fix were reverted.
    const { hash } = asLocation(buildCheckoutRedirectUrl(THANK_YOU_URL, { tier: 'retainer-weekly' }))
    expect(readCheckoutTier(hash)).toBe('retainer-weekly')
  })

  it('reproduces the ORIGINAL defect and proves the hash-only reader missed it', () => {
    // Exactly the construction the generator used before this fix.
    const broken = new URL(THANK_YOU_URL)
    broken.searchParams.set('tier', 'retainer-weekly')
    const brokenUrl = broken.toString()

    // The query landed before the fragment, which is the whole bug.
    expect(brokenUrl).toBe(
      'https://rodmen07.github.io/infraportal/?tier=retainer-weekly#/checkout-thank-you',
    )

    const { hash, search } = asLocation(brokenUrl)
    // What the page used to do: read the hash only. Nothing to find.
    expect(readCheckoutTier(hash)).toBeNull()
    // What the page does now: the live links keep working.
    expect(readCheckoutTier(hash, search)).toBe('retainer-weekly')
    expect(checkoutTierLabel(hash, search)).toBe('Retainer Weekly')
  })

  it('links already live on Stripe still resolve (compatibility path)', () => {
    // public/content/stripe_payment_links.json records the links generated on
    // 2026-06-26; their redirect URLs live on Stripe and carry the old shape.
    const artifact = JSON.parse(readSource(LINKS_ARTIFACT)) as {
      thankYouUrl: string
      tiers: { slug: string }[]
    }
    expect(artifact.tiers.length).toBeGreaterThan(0)

    for (const tier of artifact.tiers) {
      const legacy = new URL(artifact.thankYouUrl)
      legacy.searchParams.set('tier', tier.slug)
      const { hash, search } = asLocation(legacy.toString())
      expect(readCheckoutTier(hash, search), tier.slug).toBe(tier.slug)
    }
  })
})

describe('generator source drift guard (reads BOTH sources)', () => {
  const source = readSource(GENERATOR_SOURCE)

  it('builds the redirect through the shared hash-aware helper', () => {
    expect(source).toContain("from './lib/checkoutRedirect.mjs'")
    expect(source).toMatch(/buildCheckoutRedirectUrl\(\s*THANK_YOU_URL/)
  })

  it('never writes the tier into the search component of the thank-you URL', () => {
    // The exact regression: `new URL(THANK_YOU_URL)` + `searchParams.set`.
    expect(source).not.toMatch(/searchParams\.set\(\s*['"]tier['"]/)
  })

  it('previews the redirect URL in dry-run output so the field is observable', () => {
    // Before this fix the dry run printed everything EXCEPT the redirect URL,
    // so the one field carrying the defect could not be inspected without
    // creating real payment links against the live Stripe account.
    expect(source).toMatch(/redirectUrl: buildCheckoutRedirectUrl\(/)
  })

  it('still routes customers at the thank-you hash route the router handles', () => {
    // Second source of the contract: the router itself. A renamed route would
    // otherwise send every paying customer to the 404 page.
    const route = source.match(/#\/checkout-thank-you/)
    expect(route, `${GENERATOR_SOURCE} must target the checkout thank-you route`).not.toBeNull()
    expect(readSource('src/main.tsx')).toContain("hash.startsWith('#/checkout-thank-you')")
  })
})

describe('checkoutLandingParams (v1.22.1): the landing event carries the tier', () => {
  it('reads the tier from the hash position (the fixed generator shape)', () => {
    expect(checkoutLandingParams('#/checkout-thank-you?tier=retainer-weekly', '')).toEqual({
      tier: 'retainer-weekly',
      label: 'Retainer Weekly',
    })
  })

  it('reads the tier from the search position (links already live on Stripe)', () => {
    expect(checkoutLandingParams('#/checkout-thank-you', '?tier=project-deposit')).toEqual({
      tier: 'project-deposit',
      label: 'Project Deposit',
    })
  })

  it('emits an explicit unknown marker when no tier is recoverable', () => {
    expect(checkoutLandingParams('#/checkout-thank-you', '')).toEqual({
      tier: UNKNOWN_TIER_PARAM,
      label: FALLBACK_TIER_LABEL,
    })
    expect(UNKNOWN_TIER_PARAM).not.toBe('')
  })
})
