/**
 * Per-operation "Snippets" section (v1.17.3): a copyable curl command and a
 * TypeScript SDK snippet, generated by snippetModel.ts. Rendered by
 * TryItPanel (as a sibling of the Try it box) so the curl body can source the
 * visitor's live form values; otherwise pure display with no effects and no
 * browser globals at render time.
 */

import type { OperationView } from '../specModel'
import type { TryItFormModel } from '../tryIt/formModel'
import { CopyButton } from '../CopyButton'
import {
  BASE_URL_NOTE,
  POWERSHELL_NOTE,
  SDK_SOURCE_NOTE,
  buildCurlSnippet,
  buildSdkSnippet,
  type SnippetFormState,
} from './snippetModel'

function SnippetBlock({ label, text, note }: { label: string; text: string; note?: string }) {
  return (
    <div>
      <div className="flex flex-wrap items-center justify-between gap-2">
        <span className="text-scale-xs font-semibold uppercase tracking-wider text-text-muted">
          {label}
        </span>
        <CopyButton text={text} />
      </div>
      <pre className="code-surface mt-1 max-h-72 overflow-auto rounded-md bg-zinc-900/80 p-2.5 font-mono text-scale-xs leading-4 text-text-secondary">
        {text}
      </pre>
      {note && <p className="mt-1 text-scale-xs leading-4 text-zinc-600">{note}</p>}
    </div>
  )
}

export function SnippetsSection({
  serviceId,
  operation,
  model,
  state,
  baseUrl,
}: {
  serviceId: string
  operation: OperationView
  model: TryItFormModel
  /** Live Try it form state; the curl body prefers it over the spec example. */
  state?: SnippetFormState
  /** First documented server URL from the spec. */
  baseUrl?: string
}) {
  const curl = buildCurlSnippet({ operation, model, baseUrl, state })
  const sdk = buildSdkSnippet({ serviceId, operation, baseUrl })

  return (
    <details
      data-snippets={operation.operationId}
      className="mt-2 rounded-lg border border-zinc-700/40 bg-zinc-950/40"
    >
      <summary className="cursor-pointer p-3 text-scale-xs font-semibold uppercase tracking-widest text-text-secondary hover:text-accent-text">
        Snippets: curl + TypeScript SDK
      </summary>
      <div className="space-y-3 border-t border-zinc-700/30 p-3">
        <p className="text-scale-xs leading-4 text-amber-300/80">{BASE_URL_NOTE}</p>
        <SnippetBlock label="curl" text={curl} note={POWERSHELL_NOTE} />
        <SnippetBlock label="TypeScript SDK" text={sdk} note={SDK_SOURCE_NOTE} />
      </div>
    </details>
  )
}
