/**
 * specSnapshot.mjs
 *
 * Shared core of the OpenAPI spec snapshot pipeline, used by BOTH:
 *
 *   - scripts/sync-api-specs.mjs   (regenerates the committed src/api-specs/)
 *   - scripts/check-spec-drift.mjs (regenerates into a temp dir and compares)
 *
 * Keeping the build logic in one module guarantees the drift checker
 * exercises exactly the pipeline the sync script uses: if the two agreed on
 * bytes yesterday and disagree today, the source specs changed, not the
 * tooling.
 *
 * Output is deterministic (stable service order, 2-space indent, trailing
 * newline, no timestamps) so a rebuild from an unchanged source tree is
 * byte-identical to the committed snapshot. Do not add anything
 * time-dependent or environment-dependent to the generated files.
 */

import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { parse as parseYaml } from 'yaml'

const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']

/** Service ids in canonical (alphabetical) order. Directory = `${id}-service`. */
export const SERVICE_IDS = [
  'accounts',
  'activities',
  'audit',
  'automation',
  'contacts',
  'integrations',
  'opportunities',
  'projects',
  'reporting',
  'search',
  'spend',
]

export const MANIFEST_FILE_NAME = 'manifest.json'

/**
 * The manifest's provenance note. Committed verbatim in
 * src/api-specs/manifest.json, so changing this string is itself a "drift"
 * against the committed snapshot; only change it together with a resync.
 */
export const MANIFEST_NOTE =
  'Generated by scripts/sync-api-specs.mjs from the sibling microservices checkout. Do not edit by hand; run `npm run sync-specs` to refresh.'

/** Snapshot file name for a service id (e.g. "accounts" -> "accounts-service.json"). */
export function specFileName(id) {
  return `${id}-service.json`
}

function displayName(id) {
  return id.charAt(0).toUpperCase() + id.slice(1)
}

function firstSentence(text) {
  if (!text) return ''
  const joined = text.replace(/\s+/g, ' ').trim()
  const period = joined.indexOf('. ')
  return period === -1 ? joined : joined.slice(0, period + 1)
}

export function countOperations(spec) {
  let count = 0
  for (const pathItem of Object.values(spec.paths ?? {})) {
    for (const method of HTTP_METHODS) {
      if (pathItem && typeof pathItem === 'object' && method in pathItem) count += 1
    }
  }
  return count
}

/**
 * Builds the full snapshot (per-service JSON + manifest.json) from raw
 * OpenAPI YAML text. Pure with respect to the filesystem: sources in,
 * file contents out.
 *
 * @param {Array<{ id: string, text: string, label?: string }>} sources
 *   One entry per service. `label` names the origin (a path or URL) in
 *   error messages.
 * @returns {{ files: Map<string, string>, services: object[], totalOperations: number }}
 *   `files` maps output file name -> exact file content (deterministic).
 * @throws {Error} when a source is not an OpenAPI 3.x document.
 */
export function buildSnapshotFiles(sources) {
  // Canonical order: SERVICE_IDS order first, then any unknown ids
  // alphabetically (unit tests may pass a subset or extra fakes).
  const ordered = [...sources].sort((a, b) => {
    const ai = SERVICE_IDS.indexOf(a.id)
    const bi = SERVICE_IDS.indexOf(b.id)
    if (ai !== -1 && bi !== -1) return ai - bi
    if (ai !== -1) return -1
    if (bi !== -1) return 1
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0
  })

  const files = new Map()
  const services = []

  for (const { id, text, label } of ordered) {
    const origin = label ?? `${id}-service/openapi.yaml`
    const spec = parseYaml(text)

    if (typeof spec?.openapi !== 'string' || !spec.openapi.startsWith('3.')) {
      throw new Error(`${origin} is not an OpenAPI 3.x document`)
    }

    files.set(specFileName(id), JSON.stringify(spec, null, 2) + '\n')

    services.push({
      id,
      name: displayName(id),
      title: spec.info?.title ?? `${id}-service`,
      version: spec.info?.version ?? 'unknown',
      summary: firstSentence(spec.info?.description),
      operationCount: countOperations(spec),
      tags: (spec.tags ?? []).map((tag) => tag.name),
    })
  }

  const manifest = {
    note: MANIFEST_NOTE,
    openapiVersion: '3.0.3',
    services,
  }
  files.set(MANIFEST_FILE_NAME, JSON.stringify(manifest, null, 2) + '\n')

  const totalOperations = services.reduce((sum, svc) => sum + svc.operationCount, 0)
  return { files, services, totalOperations }
}

function listJsonFiles(dir) {
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.json'))
    .map((entry) => entry.name)
}

/**
 * Reads a file as git-normalized bytes: CRLF collapsed to LF. The pipeline
 * only ever writes LF and git stores LF, but a Windows working tree with
 * core.autocrlf materializes CRLF on checkout; treating that as drift would
 * make the checker cry wolf on every dev machine while the bytes in git are
 * identical. On CI (LF checkout) this normalization is a no-op and the
 * comparison stays byte-exact.
 */
function readNormalized(path) {
  return Buffer.from(readFileSync(path, 'utf8').replace(/\r\n/g, '\n'), 'utf8')
}

/**
 * Byte-compares a freshly regenerated snapshot directory against the
 * committed one, over git-normalized (LF) content; see readNormalized. Only
 * `*.json` files participate (src/api-specs/ also holds the hand-written
 * index.ts catalog, which is not generated).
 *
 * @param {string} freshDir     directory the snapshot was just regenerated into
 * @param {string} committedDir the committed snapshot directory (src/api-specs)
 * @returns {{ clean: boolean, entries: Array<{ file: string, status: 'match' | 'drift' | 'missing' | 'stale', freshBytes: number | null, committedBytes: number | null }> }}
 *   Statuses: `match` byte-identical; `drift` both exist, bytes differ;
 *   `missing` regenerated but absent from the committed dir; `stale`
 *   committed but no longer regenerated (e.g. a service removed upstream).
 *   Byte counts are of the normalized content. Entries are sorted by file
 *   name; `clean` is true iff every entry matches.
 */
export function compareSnapshotDirs(freshDir, committedDir) {
  const freshFiles = new Set(listJsonFiles(freshDir))
  const committedFiles = new Set(listJsonFiles(committedDir))
  const allFiles = [...new Set([...freshFiles, ...committedFiles])].sort()

  const entries = allFiles.map((file) => {
    const inFresh = freshFiles.has(file)
    const inCommitted = committedFiles.has(file)
    if (!inCommitted) {
      return { file, status: 'missing', freshBytes: readNormalized(join(freshDir, file)).length, committedBytes: null }
    }
    if (!inFresh) {
      return { file, status: 'stale', freshBytes: null, committedBytes: readNormalized(join(committedDir, file)).length }
    }
    const fresh = readNormalized(join(freshDir, file))
    const committed = readNormalized(join(committedDir, file))
    return {
      file,
      status: fresh.equals(committed) ? 'match' : 'drift',
      freshBytes: fresh.length,
      committedBytes: committed.length,
    }
  })

  return { clean: entries.every((entry) => entry.status === 'match'), entries }
}

/**
 * Renders a comparison report as printable lines (no colors, CI-log
 * friendly). One line per file plus a summary line.
 *
 * @param {ReturnType<typeof compareSnapshotDirs>} report
 * @returns {string[]}
 */
export function formatComparisonReport(report) {
  const lines = report.entries.map((entry) => {
    switch (entry.status) {
      case 'match':
        return `  match    ${entry.file} (${entry.committedBytes} bytes)`
      case 'drift':
        return `  DRIFT    ${entry.file} (committed ${entry.committedBytes} bytes, regenerated ${entry.freshBytes} bytes)`
      case 'missing':
        return `  MISSING  ${entry.file} (regenerated ${entry.freshBytes} bytes, no committed snapshot)`
      case 'stale':
        return `  STALE    ${entry.file} (committed ${entry.committedBytes} bytes, no longer generated from source)`
      /* v8 ignore next 2 -- statuses above are exhaustive */
      default:
        return `  ?        ${entry.file}`
    }
  })

  const bad = report.entries.filter((entry) => entry.status !== 'match').length
  lines.push('')
  lines.push(
    report.clean
      ? `OK: all ${report.entries.length} committed snapshot files are in sync with the source specs.`
      : `FAIL: ${bad} of ${report.entries.length} snapshot files differ from the source specs.`,
  )
  return lines
}
