/**
 * Committed OpenAPI snapshot catalog.
 *
 * The JSON files in this directory are generated by `npm run sync-specs`
 * (scripts/sync-api-specs.mjs) from the sibling microservices checkout and
 * committed, so the site renders the full API surface offline with no
 * network requests to any live service. Do not edit the JSON by hand.
 *
 * Full specs are loaded lazily (one Vite chunk per service) so the initial
 * bundle only carries the small manifest below.
 */

import type { OpenApiSpec } from '../features/apiDocs/openapiTypes'
import manifestJson from './manifest.json'

export interface SpecManifestService {
  id: string
  name: string
  title: string
  version: string
  summary: string
  operationCount: number
  tags: string[]
}

export interface SpecManifest {
  note: string
  openapiVersion: string
  services: SpecManifestService[]
}

export const SPEC_MANIFEST: SpecManifest = manifestJson

export const SPEC_SERVICES: SpecManifestService[] = SPEC_MANIFEST.services

export const TOTAL_OPERATIONS: number = SPEC_SERVICES.reduce(
  (sum, service) => sum + service.operationCount,
  0,
)

type SpecModule = { default: unknown }

const loaders: Record<string, () => Promise<SpecModule>> = {
  accounts: () => import('./accounts-service.json'),
  activities: () => import('./activities-service.json'),
  audit: () => import('./audit-service.json'),
  automation: () => import('./automation-service.json'),
  contacts: () => import('./contacts-service.json'),
  integrations: () => import('./integrations-service.json'),
  opportunities: () => import('./opportunities-service.json'),
  projects: () => import('./projects-service.json'),
  reporting: () => import('./reporting-service.json'),
  search: () => import('./search-service.json'),
  spend: () => import('./spend-service.json'),
}

export const SERVICE_IDS: string[] = Object.keys(loaders)

/** Loads a service's committed OpenAPI snapshot as its own lazy chunk. */
export async function loadSpec(serviceId: string): Promise<OpenApiSpec> {
  const loader = loaders[serviceId]
  if (!loader) {
    throw new Error(`unknown service id: ${serviceId}`)
  }
  const module = await loader()
  return module.default as OpenApiSpec
}
